export const listaDeIcones = {
  sair: "material-symbols-light:logout-rounded",
  home: "proicons:home",
  close: "si:close-fill",
  notificacao: "streamline-plump:ringing-bell-notification",
  pescaria: "icon-park-outline:fishing",
  visualizar: "iconamoon:eye-thin",
  editar: "akar-icons:edit",
  excluir: "material-symbols:delete-outline-rounded",
  temaDark: "tdesign:mode-dark",
  temaLight: "iconoir:sun-light",
  calendario: "solar:calendar-linear",
  plus: "ei:plus",
  pasta: "flat-color-icons:folder",
  pastaAberta: "flat-color-icons:opened-folder",
  setaPraDireita: "lets-icons:expand-right",
  setaParaEsquerda: "lets-icons:expand-left",
  foto: "raphael:photo",
  barco: "game-icons:fishing-boat",
  account: "mdi:account-cog-outline",
};
