name: Docker Image CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        run: |
          cat > .env.production
          echo "NEXT_PUBLIC_URL_API=${{ secrets.URL_API }}" >> .env.production
          echo "NEXT_PUBLIC_PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env.production
          echo "$(<.env.production)"
      - name: Build
        run: docker build . -t brunobentocaina/mapa-da-pesca-ui:${GITHUB_REF#refs/*/}
      - name: Push
        run: |
          docker login -u brunobentocaina -p ${{ secrets.DOCKER_HUB_KEY }}
          docker push brunobentocaina/mapa-da-pesca-ui:${GITHUB_REF#refs/*/}